name: Bug report
description: Report bugs
labels: ['bug']
body:
  - type: textarea
    id: steps
    attributes:
      label: Observed behavior
      description: A clear description of the expected behavior. Steps to reproducde, logs, etc.
      value: |
        1. Step
        2. Step
        3. Step
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear description of the expected behavior.
      placeholder: I expected it to...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 'Version:'
      description: Version of the software/firmware this behaviour was observed.
      placeholder: vX.X.X
    validations:
      required: false
  - type: input
    id: platform
    attributes:
      label: 'Platform:'
      description: Platform on which this behaviour was observed.
      placeholder: Windows XP
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information.
      description: Add any other context about the problem here.
      placeholder: I think this issue is related to line xx of file yy...
    validations:
      required: false
