name: Other
description: Changes that are not necessarily a feature or a bugfix
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motvation statement
      description: Why does this change need to happen?
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution/Implementation
      description: Your plan for the change
    validations:
      required: true
